services: - type: web name: api-generica-crud env: python plan: free buildCommand: apt-get install -y unixodbc-dev && pip install -r requirements.txt startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT envVars: - key: ENVIRONMENT value: production - key: DB_PROVIDER value: postgres - key: DB_POSTGRES sync: false 

services:
  - type: web
    name: mi-api
    env: python
    buildCommand: pip install -r requirements.txt
    # Aquí es donde agregas las librerías de sistema
    runtimeData:
      packages:
        - unixodbc
        - unixodbc-dev